name: rinha-2026

services:
  api1:
    image: quartet2617/rinha-backend-2026:latest
    environment:
      - ADDR=/sockets/api1.sock
      - WORKERS=4
      - GOMAXPROCS=1
      - NPROBE=2
      - GOGC=off
      - GOMEMLIMIT=140MiB
    volumes:
      - rinha-sockets:/sockets
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

  api2:
    image: quartet2617/rinha-backend-2026:latest
    environment:
      - ADDR=/sockets/api2.sock
      - WORKERS=4
      - GOMAXPROCS=1
      - NPROBE=2
      - GOGC=off
      - GOMEMLIMIT=140MiB
    volumes:
      - rinha-sockets:/sockets
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - rinha-sockets:/sockets
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "25MB"

networks:
  # bridge é o modo exigido pela spec da Rinha.
  backend:
    driver: bridge

volumes:
  rinha-sockets:
